# Generated by Django 3.0.3 on 2020-03-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratehistory',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
