# Generated by Django 3.0.3 on 2020-03-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200322_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratehistory',
            name='taxable',
            field=models.IntegerField(default=0),
        ),
    ]
