# Generated by Django 3.0.3 on 2020-03-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_ratehistory_taxable'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='auto_pagibig',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='auto_philhealth',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='auto_sss',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='auto_tax',
            field=models.IntegerField(default=1),
        ),
    ]
