# Generated by Django 3.0.3 on 2020-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200331_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='period',
            field=models.IntegerField(default=0),
        ),
    ]
