# Generated by Django 3.0.3 on 2020-03-23 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
