# Generated by Django 3.0.4 on 2020-03-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deduction', '0002_deduction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='auto',
            field=models.CharField(default='NAUTO', max_length=32),
        ),
    ]
